### ISSUE TITLE
Please help me understand the example.

### ISSUE THREAD

**Issue by dan-da** [bertptrs/tracing-mutex#35]
The provided example runs to completion just fine if I use `std::sync::Mutex`.  See [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=83a1666305b488823af6d8035d36ff03).  

But it does indeed panic when using `tracing_mutex::stdsync::Mutex`.

So it seems `tracing-mutex` is detecting a deadlock that doesn't actually exist.  a false positive.

Shouldn't the `a --> b` and `a --> c` edges be removed from the graph when `_a`, `_b`, and `_c` go out of scope and the corresponding locks are released?

I get that this is a trivial example to demonstrate out-of-order locking, but the false positive was surprising to me, especially as I saw no mention in the README.

Perhaps consider:

1. Mention about false positives in the README
2. add an example with threads that actually would deadlock using `std::sync::Mutex`?

**Comment by bertptrs** [comment]
Let me clarify things a little. The point of this library is not to detect deadlocks as they happen, but to detect the possibility of deadlocks. More practically, it helps you enforce a total ordering between your mutexes by tracking the dependencies.

As such, it doesn't make sense to delete the edges after the mutexes are released. The edges represent a code path where mutexes are acquired in a certain order. To have your multithreaded code be safe from deadlocks, all code paths, regardless of timing, should have this property. Edges are currently deleted only when their corresponding nodes are deleted, and to be honest I'm not even sure whether that's the right behaviour.

I can however clear up the example a little so that it has a small but non-zero chance of deadlocking, but probably won't. The crate will detect this regardless, and that way it should be more obvious what it's doing.

**Comment by bertptrs** [comment]
@dan-da I update the example in #36 to show a piece of code that isn't guaranteed to deadlock, but may deadlock some of the time.

In release mode, no tracing is used and you can run this a few times to see it both deadlocking and succeeding. You might need to tweak the sleep time a little to make that work if your computer is too fast.

In debug mode, tracing will be enabled, and the example is guaranteed to detect the potential deadlock and panic.

That is the point of the crate, not to panic when your code deadlocks, but to show that the code has the potential to deadlock, which may or may not surface depending on external conditions.

**Comment by dan-da** [comment]
@bertptrs thx for the clarification and for updating the example.  I will try it out.
